"""Storage contract shared by the SQLite and Postgres backends.

Every public capability the gateway relies on is declared here, and
``create_storage()`` asserts conformance at startup, so a method added to one
backend but not the other fails immediately instead of surfacing as a
runtime AttributeError (or worse, a silently skipped feature — the original
gateway-key auth shipped Postgres-only and the capability probe quietly
disabled authentication on SQLite installs).

``tests/test_storage_contract.py`` enforces the same thing statically, so
drift is caught in CI without a running gateway.
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    # ---- lifecycle ----
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def migrate(self) -> None: ...

    # ---- per-request recording ----
    def record_metrics(self, **kwargs: Any) -> None: ...
    def record_routing_decision(self, **kwargs: Any) -> None: ...
    def record_rate_limits(self, **kwargs: Any) -> None: ...
    def touch_session(self, **kwargs: Any) -> None: ...

    # ---- content importance ----
    def record_content_importance(self, content_hash: str, source: str = "request") -> None: ...
    def get_content_importance(self, content_hashes: list[str]) -> dict[str, float]: ...
    def cleanup_stale_importance(self, max_age_hours: int = 168) -> int: ...

    # ---- compression cache ----
    def get_compression_cached(self, content_hash: str, age_ratio: float) -> Optional[dict]: ...
    def put_compression_cached(
        self,
        content_hash: str,
        age_ratio: float,
        compressed: str,
        tier: str,
        tokens_before: int,
        tokens_after: int,
    ) -> None: ...
    def cache_stats(self) -> dict: ...
    def cleanup_expired_cache(self) -> int: ...

    # ---- observability aggregates ----
    def get_routing_stats(self, hours: int = 24) -> dict: ...
    def get_routing_decisions(self, hours: int = 24, limit: int = 200) -> dict: ...
    def get_session_stats(self, hours: int | None = None) -> dict: ...
    def list_sessions(self, hours: int = 24, limit: int = 200) -> list[dict]: ...
    def get_cost_summary(self, days: int = 30) -> dict: ...
    def get_metrics_timeseries(self, hours: int = 24, bucket: str = "1h") -> list[dict]: ...
    def get_audit_entries(self, **kwargs: Any) -> list[dict]: ...
    def get_rate_limit_current(self, provider: str = "anthropic") -> Optional[dict]: ...
    def get_rate_limit_trend(self, hours: int = 24, provider: str = "anthropic") -> list[dict]: ...

    # ---- gateway keys ----
    def create_gateway_key(self, name: str) -> dict: ...
    def validate_gateway_key(self, raw_key: str) -> Optional[dict]: ...
    def list_gateway_keys(self) -> list[dict]: ...
    def toggle_gateway_key(self, key_id: int, enabled: bool) -> bool: ...
    def delete_gateway_key(self, key_id: int) -> bool: ...
